language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install: "pip install -r requirements.txt"
install: "pip install -r requirements_dev.txt"
# command to run tests
script: py.test
