[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool.black]
target-version = ["py36", "py37", "py38"]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_tests = "tests"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER", "TESTS"]

[tool.poetry]
name = "pickle_secure"
version = "0.9.9"
description = "Easily create encrypted pickle files"
authors = [
    "Stephanos Kuma <spapanik21@gmail.com>",
]

license = "MIT"
readme = "README.md"
include = ["CHANGELOG.md"]

repository = "https://github.com/spapanik/pickle-secure"

keywords=["pickle", "AES", "secure storage"]
classifiers=[
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.6.0"

cryptography = "^2.0.0"

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
isort = "^4.3.0"

pytest = "^5.4.0"
pytest-cov = "^2.8.0"
coveralls = "^2.0.0"

ipython = "^7.14.0"
ipdb = "^0.13.0"

flake8 = "^3.8.0"
flake8-bugbear = "^20.1.0"
flake8-builtins = "^1.5.0"
flake8-comprehensions = "^3.2.0"
flake8-eradicate = "^0.3.0"
flake8-executable = "^2.0.0"
flake8-mutable = "^1.2.0"
flake8-tidy-imports = "^4.1.0"
